#ifndef HLD_CANFDTOOLPRO_VERSION_H
#define HLD_CANFDTOOLPRO_VERSION_H

#define HLD_APP_NAME "HLD_CANFDToolPro"
#define HLD_APP_VERSION "1.0"
#define HLD_FILE_VERSION 1,0,0,0
#define HLD_FILE_VERSION_STR "1.0.0.0"

#endif
