#include "iapupgrade.h"
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QSettings>
#include <algorithm>
#include <chrono>
#include <map>

namespace {constexpr uint32_t FlashBase=0x08000000,AppBase=0x08008000,ArgBase=0x08007000;constexpr int MaxSize=224*1024,DualBankMax=0x1e000,SectorSize=4096,WriteSize=128;}
IapUpgrade::~IapUpgrade(){cancel();}
bool IapUpgrade::start(const Options &options,SendFunction send,LogFunction log,ProgressFunction progress,FinishedFunction finished){if(running_.exchange(true))return false;if(thread_.joinable())thread_.join();options_=options;send_=std::move(send);log_=std::move(log);progress_=std::move(progress);finished_=std::move(finished);cancelled_=false;thread_=std::thread(&IapUpgrade::run,this);return true;}
void IapUpgrade::cancel(){cancelled_=true;ackCondition_.notify_all();if(thread_.joinable())thread_.join();running_=false;}
uint16_t IapUpgrade::read16(const QByteArray &d,int o){return uint16_t(uint8_t(d[o])|(uint16_t(uint8_t(d[o+1]))<<8));}
uint32_t IapUpgrade::read32(const QByteArray &d,int o){return uint32_t(uint8_t(d[o]))|(uint32_t(uint8_t(d[o+1]))<<8)|(uint32_t(uint8_t(d[o+2]))<<16)|(uint32_t(uint8_t(d[o+3]))<<24);}
uint16_t IapUpgrade::crc16(const QByteArray &data,int size){uint16_t crc=0;if(size<0)size=data.size();for(int i=0;i<size;++i){crc^=uint16_t(uint8_t(data[i]))<<8;for(int b=0;b<8;++b)crc=(crc&0x8000)?uint16_t((crc<<1)^0x1021):uint16_t(crc<<1);}return crc;}
uint32_t IapUpgrade::crc32(const QByteArray &data){uint32_t crc=0;for(const auto byte:data){crc^=uint32_t(uint8_t(byte))<<24;for(int b=0;b<8;++b)crc=(crc&0x80000000U)?(crc<<1)^0x04C11DB7U:crc<<1;}return crc;}
void IapUpgrade::feed(uint32_t canId,const QByteArray &data){if(!running_||canId!=options_.canId||data.isEmpty())return;std::lock_guard lock(mutex_);receiveBuffer_.append(data);while(!receiveBuffer_.isEmpty()&&uint8_t(receiveBuffer_[0])!=options_.targetAddress)receiveBuffer_.remove(0,1);if(receiveBuffer_.size()<=12)return;const int payload=read16(receiveBuffer_,10);if(payload>256){receiveBuffer_.clear();return;}const int total=payload+14;if(receiveBuffer_.size()<total)return;auto candidate=receiveBuffer_.left(total);receiveBuffer_.remove(0,total);if(read16(candidate,total-2)==crc16(candidate,total-2)){ack_=candidate;waiting_=false;ackCondition_.notify_all();}}
QByteArray IapUpgrade::packet(uint16_t command,uint32_t address,uint16_t length,const QByteArray &payload)const{QByteArray out(14+payload.size(),'\0');out[0]=char(options_.targetAddress);out[1]=char(0x41);out[2]=char(command);out[3]=char(command>>8);for(int i=0;i<4;++i)out[4+i]=char(address>>(8*i));out[8]=char(length);out[9]=char(length>>8);out[10]=char(payload.size());out[11]=char(payload.size()>>8);std::copy(payload.begin(),payload.end(),out.begin()+12);const auto crc=crc16(out,out.size()-2);out[out.size()-2]=char(crc);out[out.size()-1]=char(crc>>8);return out;}
QByteArray IapUpgrade::sendAndWait(const QByteArray &request,int timeoutMs){{std::lock_guard lock(mutex_);receiveBuffer_.clear();ack_.clear();waiting_=true;}if(!send_(request))return {};std::unique_lock lock(mutex_);ackCondition_.wait_for(lock,std::chrono::milliseconds(timeoutMs),[this]{return !waiting_||cancelled_;});waiting_=false;return ack_;}
QByteArray IapUpgrade::loadHex(const QString &path){QFile file(path);if(!file.open(QIODevice::ReadOnly|QIODevice::Text))return {};std::map<uint32_t,uint8_t> memory;uint32_t base=0;while(!file.atEnd()){const auto line=file.readLine().trimmed();if(line.isEmpty())continue;if(line[0]!=':')return {};bool ok=true;auto byte=[&](int pos){bool x=false;int v=line.mid(pos,2).toInt(&x,16);ok&=x;return uint8_t(v);};const int length=byte(1);const uint16_t address=(uint16_t(byte(3))<<8)|byte(5);const uint8_t type=byte(7);uint8_t sum=uint8_t(length+(address>>8)+address+type);QByteArray bytes;for(int i=0;i<length;++i){const auto v=byte(9+i*2);bytes.append(char(v));sum=uint8_t(sum+v);}sum=uint8_t(sum+byte(9+length*2));if(!ok||sum!=0)return {};if(type==0){const uint32_t absolute=base+address;for(int i=0;i<bytes.size();++i){memory[absolute+i]=uint8_t(bytes[i]);}}else if(type==1)break;else if(type==4&&bytes.size()>=2)base=((uint32_t(uint8_t(bytes[0]))<<8)|uint8_t(bytes[1]))<<16;}if(memory.empty())return {};bool hasBootloader=false;uint32_t min=UINT32_MAX,max=0;std::map<uint32_t,uint8_t> appMemory;for(const auto &[address,value]:memory){if(address<AppBase){hasBootloader=true;}else{appMemory[address]=value;min=std::min(min,address);max=std::max(max,address);}}if(appMemory.empty()){if(log_)log_("错误：HEX 文件未包含 APP 地址段 (>= 0x08008000) 的数据！");return {};}if(hasBootloader&&log_){log_("提示：检测到 HEX 文件包含 Bootloader/ARG 地址段 (< 0x08008000)，已自动剥离，仅提取 APP 升级代码！");}QByteArray result(int(max-AppBase+1),char(0xff));for(const auto &[address,value]:appMemory){result[int(address-AppBase)]=char(value);}return result;}
QByteArray IapUpgrade::loadFirmware(const QString &path){QFile file(path);if(options_.dualBank||path.endsWith(".dbiap",Qt::CaseInsensitive)){if(!file.open(QIODevice::ReadOnly))return {};return file.readAll();}if(path.endsWith(".hex",Qt::CaseInsensitive))return loadHex(path);if(!file.open(QIODevice::ReadOnly))return {};QByteArray raw=file.readAll();if(raw.isEmpty())return {};if(raw.size()>0x8000){uint32_t headerResetHandler=read32(raw,4);uint32_t appResetHandler=read32(raw,0x8000+4);bool isBootloaderHeader=(headerResetHandler>=0x08000000&&headerResetHandler<0x08008000&&(appResetHandler&0xFFFE0000)==0x08000000&&appResetHandler>=0x08008000);if(isBootloaderHeader||path.contains("jlink",Qt::CaseInsensitive)){if(log_)log_(QString("提示：检测到为含 Bootloader 的合并固件（大小 %1 字节），已自动剥离前 32KB (0x8000 字节) Bootloader 头，提取 APP 升级代码！").arg(raw.size()));return raw.mid(0x8000);}}return raw;}
QString resumePath(const IapUpgrade::Options &o){return QDir(QFileInfo(o.firmwarePath).absolutePath()).filePath(QString(".%1_%2.iap.ini").arg(QFileInfo(o.firmwarePath).baseName()).arg(o.canId,0,16));}
int IapUpgrade::loadResume(const QByteArray &firmware,uint32_t crc){QSettings s(resumePath(options_),QSettings::IniFormat);if(s.value("size").toInt()!=firmware.size()||s.value("crc").toUInt()!=crc)return 0;const int saved=qBound(0,s.value("index").toInt(),firmware.size());return (saved/SectorSize*SectorSize)/WriteSize*WriteSize;}
void IapUpgrade::saveResume(int index){QSettings s(resumePath(options_),QSettings::IniFormat);s.setValue("size",firmwareSize_);s.setValue("crc",firmwareCrc_);s.setValue("index",index);s.sync();}
void IapUpgrade::clearResume(){QFile::remove(resumePath(options_));}
bool IapUpgrade::enterIap(){const auto req=packet(1,0,1,QByteArray(1,char(1)));for(int i=0;i<=120&&!cancelled_;++i){auto ack=sendAndWait(req,180);if(ack.size()>12&&read16(ack,2)==1&&uint8_t(ack[12])==1){log_("已进入 IAP");std::this_thread::sleep_for(std::chrono::milliseconds(500));return true;}std::this_thread::sleep_for(std::chrono::milliseconds(120));if(i&&i%20==0)log_(QString("仍在等待 bootloader，已尝试 %1 次").arg(i));}return false;}
bool IapUpgrade::probeTarget(){if(options_.targetAddress!=1)return true;log_("正在通过 LLC 网关探测 PFC Bootloader...");for(int retry=0;retry<8&&!cancelled_;++retry){auto ack=sendAndWait(packet(0x30,0,0,{}),1200);if(ack.size()>=32&&read16(ack,2)==0x30&&uint8_t(ack[28])==1){const int major=uint8_t(ack[12]),minor=uint8_t(ack[13]);const uint32_t caps=read32(ack,16);log_(QString("PFC Bootloader 已就绪：协议 %1.%2，能力=0x%3，路径=CAN→LLC→UART→PFC").arg(major).arg(minor).arg(caps,8,16,QChar('0')).toUpper());return true;}std::this_thread::sleep_for(std::chrono::milliseconds(300));}log_("PFC Bootloader 探测失败：未收到经 LLC 转发的有效能力应答");return false;}
bool IapUpgrade::manageBank(){uint16_t cmd=0x20;uint32_t bank=0;if(options_.bankAction==2){cmd=0x21;bank=0;}else if(options_.bankAction==3){cmd=0x21;bank=1;}else if(options_.bankAction==4){cmd=0x22;bank=0;}else if(options_.bankAction==5){cmd=0x22;bank=1;}else if(options_.bankAction==6)cmd=0x23;else if(options_.bankAction==7)cmd=0x24;auto ack=sendAndWait(packet(cmd,bank,0,{}),8000);if(cmd==0x20){if(ack.size()<25||read16(ack,2)!=cmd)return false;const int o=12;const QString current=uint8_t(ack[o])?"Bank B":"Bank A";const QString va=uint8_t(ack[o+3])?"有效":"无效";const QString vb=uint8_t(ack[o+4])?"有效":"无效";const uint32_t id=read32(ack,o+9);log_(QString("当前运行：%1；Bank A：%2；Bank B：%3；MAP=0x%4，BMD=0x%5，状态=%6，试启动=%7，IAP ID=0x%8").arg(current,va,vb).arg(uint8_t(ack[o+1]),0,16).arg(uint8_t(ack[o+2]),0,16).arg(uint8_t(ack[o+7])).arg(uint8_t(ack[o+8])).arg(id,0,16).toUpper());return true;}if(cmd==0x21){if(ack.size()<13||read16(ack,2)!=cmd)return false;log_(QString("Bank %1 校验结果：%2").arg(bank?'B':'A').arg(uint8_t(ack[12])?"有效":"无效"));return true;}const bool ok=ack.isEmpty()||read16(ack,2)==cmd;if(ok&&(cmd==0x22||cmd==0x24)){send_(packet(0x25,0,0,{}));log_("Bank 切换命令已提交，设备正在复位");}else if(ok&&cmd==0x23)log_("当前 Bank 已确认");return ok;}
bool IapUpgrade::beginDualBank(int size,uint32_t crc){QByteArray p(8,'\0');for(int i=0;i<4;++i){p[i]=char(uint32_t(size)>>(8*i));p[4+i]=char(crc>>(8*i));}auto a=sendAndWait(packet(6,0,8,p),3000);return a.size()>=12&&read16(a,2)==6;}
bool IapUpgrade::verifyDualBank(){auto a=sendAndWait(packet(7,0,0,{}),8000);return a.size()>=12&&read16(a,2)==7;}
bool IapUpgrade::commitDualBank(){auto a=sendAndWait(packet(8,0,0,{}),5000);const bool ok=a.isEmpty()||read16(a,2)==8;if(!ok||!send_(packet(0x25,0,0,{})))return false;if(options_.targetAddress!=1)return true;log_("PFC 已提交新 Bank，等待复位后重新建立 LLC→UART→PFC 链路...");std::this_thread::sleep_for(std::chrono::seconds(5));if(!enterIap()||!probeTarget()){log_("PFC 新 Bank 复位后未能重新上线，不能判定升级成功");return false;}if(!exitIap()){log_("PFC 新 Bank 已在线，但退出 IAP 失败");return false;}log_("PFC 新 Bank 已重新上线并通过能力探测");return true;}
bool IapUpgrade::writeFlash(const QByteArray &firmware){int index=resumeIndex_;auto lastLogTime=std::chrono::steady_clock::now();while(index<firmware.size()&&!cancelled_){QByteArray block(WriteSize,char(0xff));const int copy=qMin(WriteSize,firmware.size()-index);std::copy_n(firmware.constBegin()+index,copy,block.begin());const uint32_t address=(options_.dualBank?FlashBase:AppBase)+index;bool ok=false;for(int retry=0;retry<5&&!cancelled_;++retry){auto ack=sendAndWait(packet(3,address,WriteSize,block),3000);if(ack.size()>=12&&read16(ack,2)==3&&read32(ack,4)==address&&read16(ack,8)==WriteSize){ok=true;break;}std::this_thread::sleep_for(std::chrono::milliseconds(300));}if(!ok){resumeIndex_=(index/SectorSize*SectorSize)/WriteSize*WriteSize;saveResume(resumeIndex_);log_(QString("写入失败：0x%1").arg(address,8,16,QChar('0')));return false;}index+=WriteSize;resumeIndex_=qMin(index,firmware.size());int currentPercent=qMin(99,index*100/firmware.size());progress_(currentPercent);auto now=std::chrono::steady_clock::now();auto elapsedMs=std::chrono::duration_cast<std::chrono::milliseconds>(now-lastLogTime).count();if(elapsedMs>=100||index>=firmware.size()){lastLogTime=now;log_(QString("写入 Flash 进度：%1% (%2/%3 字节)").arg(currentPercent).arg(qMin(index,firmware.size())).arg(firmware.size()));}}return !cancelled_;}
bool IapUpgrade::writeChecksum(int size,uint32_t crc){if(log_)log_("正在写入 CRC32 签名与固件元数据 (0x08007000)...");QByteArray payload(WriteSize,char(0));for(int i=0;i<4;++i){payload[i]=char(uint32_t(size)>>(8*i));payload[4+i]=char(crc>>(8*i));}for(int retry=0;retry<10&&!cancelled_;++retry){auto ack=sendAndWait(packet(4,ArgBase,WriteSize,payload),3000);if(ack.size()>=12&&read16(ack,2)==4&&read16(ack,8)==WriteSize)return true;}return false;}
bool IapUpgrade::writeAddress(){if(options_.newCanId==0||options_.newCanId>0x1FFFFFFFU)return false;if(log_)log_(QString("写入新的 IAP 地址 0x%1").arg(options_.newCanId,0,16,QChar('0')).toUpper());for(int retry=0;retry<5&&!cancelled_;++retry){auto ack=sendAndWait(packet(5,options_.newCanId,0,{}),3000);if(ack.size()>=12&&read16(ack,2)==5)return true;}return false;}
bool IapUpgrade::exitIap(){if(log_)log_("正在退出 IAP 模式并跳转运行 APP...");for(int retry=0;retry<5&&!cancelled_;++retry){auto ack=sendAndWait(packet(0,0,0,{}),1500);if(ack.size()>=12&&read16(ack,2)==0)return true;}return false;}
void IapUpgrade::run(){bool success=false;if(options_.bankAction){success=enterIap()&&probeTarget()&&manageBank();if(success&&options_.bankAction<=3)exitIap();}else if(options_.addressOnly){success=enterIap()&&probeTarget()&&writeAddress();if(success){progress_(100);log_("IAP 地址保存成功，设备复位后使用新地址；0xAA55 仍可救援。");}}else{const auto firmware=loadFirmware(options_.firmwarePath);const int limit=options_.dualBank?DualBankMax:MaxSize;if(firmware.isEmpty()||firmware.size()>limit)log_(QString("固件大小异常：%1 bytes").arg(firmware.size()));else{firmwareSize_=firmware.size();firmwareCrc_=crc32(firmware);log_(QString("固件加载：%1 bytes，CRC32=0x%2").arg(firmware.size()).arg(firmwareCrc_,8,16,QChar('0')));resumeIndex_=loadResume(firmware,firmwareCrc_);for(int attempt=1;attempt<=3&&!cancelled_&&!success;++attempt){log_(QString("第 %1 次升级尝试").arg(attempt));if(options_.dualBank)success=enterIap()&&probeTarget()&&beginDualBank(firmware.size(),firmwareCrc_)&&writeFlash(firmware)&&verifyDualBank()&&commitDualBank();else success=enterIap()&&probeTarget()&&writeFlash(firmware)&&writeChecksum(firmware.size(),firmwareCrc_)&&exitIap();if(!success&&!cancelled_)std::this_thread::sleep_for(std::chrono::seconds(5));}if(success){clearResume();progress_(100);log_(options_.dualBank?"双 Bank 升级完成，设备将从新 Bank 启动":"升级完成");}}}running_=false;finished_(success);}
